/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solus.sdk;

import com.solus.sdk.model.BaseResponse;
import com.solus.sdk.model.ErrorResponse;
import com.solus.sdk.model.Payment;
import com.solus.sdk.model.Response;
import com.solus.sdk.model.types;
import com.solus.sdk.noebscall.NOEBSClient;


/*
* How to use noebs SDK
* - special payment:
* use types.SpecialPayment
* - Zain:
* use types.ZainTopUp
* - MTN:
* use types.MTNTopUp
* - Sudani:
* use types.SudaniTopUp
* - NEC:
* use types.NEC
* - E15:
* use types.E15
* */
public class Library {
    public static void main(String[] args) {
		Payment payment = new Payment("gdljdfslkgjf;lgks", "123456789101112131", "2206", "1234", 10f);
		NOEBSClient noebsClient = new NOEBSClient();
		BaseResponse<?> response = noebsClient.getResponse(payment);
		Object object = response.getResponse();
		if(object instanceof Response) {
			System.out.println(true);
		}else if(object instanceof ErrorResponse){
			ErrorResponse err =(ErrorResponse)object;
			System.out.println(err.getResponseMessage());
			System.out.println(false);
		}else {
			System.out.println("Error");
		}
		

	}
}
