/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solussdk;

import org.junit.Test;

import com.solus.sdk.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
       
    }
}
